### ISSUE TITLE
Issues with HabTech2's Solar Arrays

### ISSUE THREAD

**Issue by Delta-86** [Aebestach/WeatherDrivenSolarPanel#3]
When this mod is installed, it causes the tracking solar arrays to always show iROSA while making them unable to be interacted with. Since it's unlikely however that these parts would be used on a planet, it would perhaps be best to make the mod not target them.

**Comment by Aebestach** [comment]
Hello, @Delta-86.
I just installed HabTech2. went into the game and tested it against tracking solar arrays, and I didn't find the problem you're talking about to exist. They all functioned fine in my tests and did not appear to show iROSA all the time.
Without more information, I'm guessing the problem may be with other mods also installed that are affecting HabTech2.
If it is convenient for you, you can send a short video or picture to describe your problem.

Attached - Test Environment
KSP 1.12.5
Volume Clouds
WDSP v4.4
HabTech2 v1.0.0
and their dependence.
